// fallback-test
// Generated by Forge Mock Engineer @ 2026-05-07T10:00:53.363Z
// Source: Axing Studio V2

export interface TaskSpec {
  id: string;
  title: string;
  type: 'oracle' | 'forge' | 'hermes';
  input: Record<string, unknown>;
  status: 'blocked' | 'queued' | 'running' | 'completed' | 'failed' | 'retrying';
}

export function validateTaskSpec(input: unknown): input is TaskSpec {
  if (typeof input !== 'object' || input === null) return false;
  const t = input as Record<string, unknown>;
  return typeof t.id === 'string'
    && typeof t.title === 'string'
    && ['oracle','forge','hermes'].includes(t.type as string)
    && typeof t.input === 'object';
}

export function parseInput(raw: string): Record<string, unknown> {
  try { return JSON.parse(raw); } catch { return {}; }
}

// Smoke test (run: npx tsx this-file.ts)
if (typeof require !== 'undefined' && require.main === module) {
  console.log(validateTaskSpec({
    id: 'test-1',
    title: 'test fallback',
    type: 'forge',
    input: {},
    status: 'queued',
  }) ? 'PASS' : 'FAIL');
}
